app/models.py
from app import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

# Banco de dados. Responsável pela criação dos Tickets
class Ticket(db.Model):

    id              = db.Column(db.Integer, primary_key=True)
    title           = db.Column(db.String(100), nullable=False)
    description     = db.Column(db.Text, nullable=False)
    status          = db.Column(db.String(20), default='Aberto')
    created_at      = db.Column(db.DateTime, server_default=db.func.now())

    user_id         = db.Colmn(db.Integer, db.ForeignKey('user.id'), nullable=False)        
    user            = db.relationship('User', back_populates='tickets')


    def __repr__(self):
        return f'<Ticket {self.id} - {self.title}>'


# tabela do usuário e senha. Com uma criptografia de nível hash. Transformando a senha do usuário um texto aleatório.

class User(db.Model, UserMixin):

    id              = db.Column(db.Integer, primary_key=True) # ID do usuário
    username        = db.Column(db.String(150), unique=True, nullable=False) # Armaneza o nome do usuário
    password_hash   = db.Column(db.String(128), nullable=False) # Armazena a senha do usuário
    is_admin        = db.Column(db.Boolean, default=False) # Define as permissões, Admin ou User.

    tickets         = db.relationship('Ticket', back_populates='user')


    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager




# Configuração do banco de dados
db = SQLAlchemy()

# app = Flask(__name__)

def create_app():
    app = Flask(

        __name__,
        template_folder='templates',
        static_folder='static'
    )

    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///tickets.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['SECRET_KEY'] = 'troque_esta_chave_por_uma_secreta!' # Sessões de Login

    db.init_app(app)


    # Configura o Flask-Login
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    from app.models import User
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))
    



    # Registra Blueprints
    from app.routes import main
    app.register_blueprint(main)
    from app.routes_auth import auth
    app.register_blueprint(auth)


    from app.routes_admin import admin
    app.register_blueprint(admin)

    return app

app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from app.models import Ticket
from app import db

main = Blueprint('main', __name__)


@main.route('/')
def  index():
    tickets = Ticket.query.order_by(Ticket.id.desc()).all()
    return render_template('index.html', tickets=tickets)


@main.route('/create', methods=['GET', 'POST'])

def create_ticket():
@login_required

    if request.method == 'POST':
        title = request.form['title']
        desc = request.form['description']
        new = Ticket(title=title, description=desc)
        new = Ticket(
            title=title,
            description=desc,
            user_id=current_user.id # Vincula o Ticket ao usuário logado
        )
        db.session.add(new)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('create_ticket.html')

app/templates/admin_dashboard.html
<!DOCTYPE html>
<html>
<head><title>Painel Admin</title></head>
<body>
    <h1>painel de Administração</h1>
    <p><a href="{{ url_for('main.index') }}">Voltar à Lista Pública</a></p>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
        {% for m in messages %}
            <li>{{ m }}</li>
        {% endfor %}
        </ul>
        {% endif %}
    {% endwith %}
    
    <table>
        <thead>
            <tr><th>ID</th><th>Título</th><th>Status</th><th>Ações</th></tr>
        </thead>
        <tbody>
            {% for ticket in tickets %}
                <tr>
                    <td>{{ ticket.id }}</td>
                    <td>{{ ticket.title }}</td>
                    <td>{{ ticket.status }}</td>
                    <td>{{ ticket.user.username }}</td> <!--Coluna autor-->
                    <td>
                        <a href="{{ url_for('admin.edit_ticket', ticket_id=ticket.id)}}">Editar</a>
                        <form action="{{ url_for('admin.delete_ticket', ticket_id=ticket.id) }}" method="POST" style="display: inline;">
                            <button type="submit" onclick="return confirm('Excluir este chamado?');">Excluir</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
        </tbody>
    </table>

    <h2>Gerenciar Usuários</h2>
    <table>
        <thead>
            <tr><th>Usuário</th><th>Admin?</th><th>Ações</th></tr>
        </thead>
        <tbody>
            {% for u in users %}
                <tr>
                    <td>{{ u.username }}</td>
                    <td>{{ '✅' if u.is_admin else '❌'}}</td>
                    <td>
                        {% if u.id != current_user %}
                            <form action="{ url_for('admin.toggle_admin', user_id=u.id)}" method="POST" style="display:inline;">
                                {% if u.is_admin %}
                                    <button type="submit">Rebaixar</button>
                                {% else %}
                                    <button type="submit">Promover</button>
                                {% endif%}
                            </form>
                        {% else %}
                            - <!-- Não permitir você alterar o seu próprio usuário -->
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <script>
        setInterval(function() {
            window.location.reload();
        }, 10000)
    </script>
</body>
</html>

app/templates/create_ticket.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criar Chamado</title>
</head>
<body>
    <h1>Criar Chamado</h1>
    <form method="post">
        <label>Título:<br><input name="title" required></label><br>
        <label>Descrição:<br><textarea name="description" required></textarea></textarea></label><br>
        <button type="submit">Enviar</button>
    </form>
    <a href="{{ url_for('main.index') }}">Voltar</a>
</body>
</html>

app/templates/edit_ticket.html
<!DOCTYPE html>
<html>
<head><title>Editar Chamados</title></head>
<body>
    <h1>Editar Chamado #{{ ticket.id }}</h1>
    <form method="POST">
        
        <label>Título:<br>
            <input name="title" value="{{ ticket.title }}" required>

        </label><br>

        <label>Descrição:<br>
            <textarea name="description" required>{{ ticket.description }}</textarea>

        </label><br>

        <label>Status:<br>
            <select name="status">
                <option value="Aberto" {% if ticket.status=='Aberto' %}selected{% endif %}>Aberto</option>
                <option value="Em andamento" {% if ticket.status=='Em andamento' %}selected{% endif %}>Em andamento</option>
                <option value="Resolvido" {% if ticket.status=='Resolvido' %}selected{% endif %}>Resolvido</option>
            </select>
        </label><br>
        <button type="submit">Salvar</button>
    </form>
    <p><a href="{{ url_for('admin.dashboard') }}">Voltar</a></p>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chamados</title>
</head>
<body>

    {% if current_user.is_authenticated %}
        <p><a href="{{ url_for('admin.dashboard')}}">Painel Admin</a></p>
    {% endif %}

    {% if current_user.is_authenticated %}
        <p>Olá, {{ current_user.username }}! <a href="{{ url_for('auth.logout') }}">Sair</a></p>
    {% else %}
        <p>
            <a href="{{ url_for('auth.login') }}">Login</a>
            <a href="{{ url_for('auth.register') }}">Registrar</a>
        </p>
    {% endif %}


    <h1>Lista de Chamados</h1>
    <a href="{{ url_for('main.create_ticket')}}">Novo Chamado</a>

    <ul>
    {%for t in tickets %}
        <li>
            <strong>#{{ t.id }} {{ t.title}}</strong> - {{ t.status }}<br>
            <em>Criado por: {{ t.user.username }}</em><br> <!--Mostra o nome do autor-->
            {{ t.description }}

        </li>
    {% else %}
        <li>Nenhum chamado aberto.</li>
    {% endfor %}
    </ul>


    <script>
        setInterval(function() {
            window.location.reload();
        }, 10000)
    </script>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<head><title>Registro</title></head>
<body>
    <h1>Registro</h1>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
        {% for m in messages %}
            <li>{{ m }}</li>
        {% endfor %}
        </ul>
        {% endif %}
    {% endwith %}
        <form method="POST">
            <label>Usuário:
                <input type="text" name="username" placeholder="Seu nome..." required>
            </label>

            <label>Senha:
                <input type="password" name="password" placeholder="Sua senha..." required>
            </label>
            <label>
                <input type="checkbox" name="remember"> Me lembrar
            </label>
            <button type="submit">Entrar</button>
        </form>

        <p>Não tem conta? <a href="{{ url_for('auth.register') }}">Registrar-se</a></p>


</body>

app/templates/register.html
<!DOCTYPE html>
<head><title>Registro</title></head>
<body>
    <h1>Registro</h1>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
        {% for m in messages %}
            <li>{{ m }}</li>
        {% endfor %}
        </ul>
        {% endif %}
    {% endwith %}
        <form method="POST">
            <label>Usuário:
                <input type="text" name="username" placeholder="Seu nome..." required>
            </label>

            <label>Senha:
                <input type="password" name="password" placeholder="Sua senha..." required>
            </label>
            <button type="submit">Registrar</button>
        </form>

        <p>Já tem conta? <a href="{{ url_for('auth.login') }}">Login</a></p>


</body>